app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name='delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo'),
]

memo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

class Memo(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

app/forms.py
from django.forms import ModelForm
from .models import Memo

class MemoForm(ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'text']

app/views.py
from django.shortcuts import render, redirect
from .models import Memo
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from .forms import MemoForm


def index(request):
    memos = Memo.objects.all().order_by('-updated_datetime')
    return render(request, 'app/index.html', {'memos': memos})


def detail(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    return render(request, 'app/detail.html', {'memo': memo})


def new_memo(request):
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MemoForm
    return render(request, 'app/new_memo.html', {'form': form})


@require_POST
def delete_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    memo.delete()
    return redirect('app:index')


def edit_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    if request.method == "POST":
        form = MemoForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MemoForm(instance=memo)
    return render(request, 'app/edit_memo.html', {'form': form, 'memo': memo})

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Memo的なやつ</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <h1>Memo的なやつ</h1>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

app/templates/app/detail.html
{% extends 'app/base.html' %}

{% block content %}
    <div>
        <a href="{% url 'app:index' %}">戻る</a>
    </div>
    <h2>{{ memo.title }}</h2>
    <div>
        {{ memo.text |linebreaks |urlize }}
    </div>

    <button><a class="btn" href="{% url 'app:edit_memo' memo.pk %}">編集</a></button>
    <form method="POST" action="{% url 'app:delete_memo' memo.pk %}">
        {% csrf_token %}
        <button class="btn" type="submit" onclick="return confirm('削除しますか');">削除</button>
    </form>
{% endblock %}

app/templates/app/edit_memo.html
{% extends 'app/base.html' %}

{% block content %}
    <a href="{% url 'app:detail' memo.id %}">戻る</a>
    <form action="{% url 'app:edit_memo' memo.id %}" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <th>タイトル</th>
                <td>{{ form.title }}</td>
            </tr>
            <tr>
                <th>テキスト</th>
                <td>{{ form.text }}</td>
            </tr>
        </table>
        <button class="btn" type="submit">保存</button>
    </form>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% block content %}
    <a class="btn" href="{% url 'app:new_memo' %}">新規メモ作成</a>
    {% for memo in memos %}
        <a href="{% url 'app:detail' memo.id %}">
            <div class="size">
                {{ memo }}
                <span class="updated_datetime">{{ memo.updated_datetime }}</span>
            </div>
        </a>
    {% endfor %}
{% endblock %}

app/templates/app/new_memo.html
{% extends 'app/base.html' %}
{% block content %}
    <div>
        <a href="{% url 'app:index' %}">戻る</a>
        <form action="{% url 'app:new_memo' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">保存</button>
        </form>
    </div>
{% endblock %}